services:
  frontend:
    build: ../frontend
    ports:
      - '5173:80'
    depends_on:
      - backend

  backend:
    build: ../backend
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/apexmetrics_db
      - SPRING_DATASOURCE_USERNAME=apexuser
      - SPRING_DATASOURCE_PASSWORD=apexpass
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: apexmetrics_db
      POSTGRES_USER: apexuser
      POSTGRES_PASSWORD: apexpass
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
